### ISSUE TITLE
Request for Code Sharing of the Paper 'Learning 'O' Helps for Learning More: Handling the Unlabeled Entity Problem for Class-incremental NER'

### ISSUE THREAD

**Issue by livosr** [rtmaww/O_CILNER#1]
Hello,

While reading the ACL2023 paper "Learning 'O' Helps for Learning More: Handling the Unlabeled Entity Problem for Class-incremental NER", I clicked on the open-source code link provided in the paper and was directed to this page. However, I only see a readme file here. Could you kindly let me know when you would be able to share the code? Thank you.

**Comment by rtmaww** [comment]
Thanks for your interest in our work. We have uploaded the code.  If you have any questions or need further assistance, please let us know.

**Comment by livosr** [comment]
Thank you
